apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-provider
  labels:
    app: status-provider
spec:
    replicas: 1
    selector:
        matchLabels:
        app: status-provider
    template:
        metadata:
        labels:
            app: status-provider
        spec:
          containers:
          - name: status-provider
            image: docker.kamigen.xyz/status-provider:latest
            ports:
            - containerPort: 8080
              imagePullSecrets:
                - name: regcrednexus

---
apiVersion: v1
kind: Service
metadata:
  name: status-provider-service
spec:
  selector:
    app: status-provider
  ports:
    - name: status-provider
      protocol: TCP
      port: 80
      targetPort: 8080

